name: Java FX Hello World

on:
  push:
    tags:
      - "v*" 

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Descargar / Instalar dependencias
        run: |
          wget https://download2.gluonhq.com/openjfx/21.0.10/openjfx-21.0.10_linux-x64_bin-sdk.zip
          unzip openjfx-21.0.10_linux-x64_bin-sdk.zip
      
      - name: Compilar y crear JAR
        run: |
          mkdir -p build
          javac --module-path javafx-sdk-21.0.10/lib --add-modules javafx.controls -d build javafx-hello-todo/src/dam/optativa/HelloWorldFx.java
          jar --create --file=build/HelloWorldFx.jar --manifest=javafx-hello-todo/manifest/MANIFEST.MF -C build .

      - name: Path del directorio
        run: ls

      - name: Construir ejecutable
        run: jpackage --input build --name HelloWorldFx --main-jar HelloWorldFx.jar --main-class dam.optativa.HelloWorldFx --type deb --module-path javafx-sdk-21.0.10/lib --add-modules javafx.controls

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: HelloWorldFx-Executable
          path: HelloWorldFx.deb

      - name: Release
        use: actions/action-gh-release@v2
        if: github.ref_type=='tag'
        with: 
          files: "*.deb"

      #- name: Ejecutar tests con Gradle
      #  run: ./gradlew test
